<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-DO4RSNU" failures="1" tests="3" name="TDC AUTOMATION TEST1" time="29.769" errors="0" timestamp="20 Nov 2022 01:04:11 GMT">
  <testcase classname="com.tdc.lms.testcases.LoginPageTest" name="invalidEmail" time="4.299">
    <failure type="java.lang.AssertionError" message="expected [There is no user record corresponding to this identifier.The user may have been deleted. (auth/user-not-found).] but found [There is no user record corresponding to this identifier. The user may have been deleted. (auth/user-not-found).]">
      <![CDATA[java.lang.AssertionError: expected [There is no user record corresponding to this identifier.The user may have been deleted. (auth/user-not-found).] but found [There is no user record corresponding to this identifier. The user may have been deleted. (auth/user-not-found).]
at com.tdc.lms.testcases.LoginPageTest.invalidEmail(LoginPageTest.java:26)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- invalidEmail -->
  <testcase classname="com.tdc.lms.testcases.LoginPageTest" name="login" time="4.444"/>
  <testcase classname="com.tdc.lms.testcases.LogoutPageTest" name="logOut" time="3.501"/>
  <testcase classname="com.tdc.lms.base.BaseTests" name="@BeforeTest initializeDriver" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest initializeDriver -->
  <testcase classname="com.tdc.lms.base.BaseTests" name="@AfterTest tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest tearDown -->
</testsuite> <!-- TDC AUTOMATION TEST1 -->
